module.exports = {
  content: ["./**/*.html", "./server.js", "./assets/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#fff0e8",
        "on-tertiary-fixed": "#002113",
        surface: "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#ffd3bf",
        "on-primary": "#ffffff",
        "on-background": "#111111",
        "surface-container-high": "#f5f5f5",
        "on-surface-variant": "#45464d",
        "surface-container-low": "#ffffff",
        "surface-bright": "#ffffff",
        "surface-variant": "#f0f0f0",
        "on-surface": "#111111",
        "surface-container": "#f7f7f7",
        "surface-container-highest": "#ededed",
        "on-tertiary-container": "#009668",
        secondary: "#d64206",
        background: "#ffffff",
        "primary-fixed": "#fff0e8",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        tertiary: "#000000",
        outline: "#76777d",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed-dim": "#4edea3",
        primary: "#000000",
        error: "#ba1a1a",
        "on-primary-container": "#5f1f00",
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-container": "#002113",
        "on-secondary-container": "#fefcff",
        "secondary-fixed-dim": "#ffd3bf",
        "surface-dim": "#f0f0f0",
        "on-secondary-fixed": "#3b1200",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#8f2a00",
        "on-error-container": "#93000a",
        "inverse-surface": "#222222",
        "on-primary-fixed-variant": "#7a2800",
        "inverse-primary": "#ffd3bf",
        "surface-tint": "#d64206",
        "secondary-container": "#d64206",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ffffff",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xxl: "64px",
        base: "4px",
        "container-max": "1280px",
        xl: "40px",
        gutter: "20px",
        lg: "24px",
        xs: "4px",
        sm: "8px",
        "margin-mobile": "16px",
        md: "16px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }]
      }
    }
  }
};
